services:
  property:
    image: kondo-movie-maker
    container_name: kondo-movie-maker
    build: 
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - kondo-network

networks:
  kondo-network:
    external: true