services:
  property:
    image: kondo-movie-maker
    container_name: kondo-movie-maker
    build: 
      context: .
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./secrets:/secrets:ro  # Mount secrets as read-only
    ports:
      - 8080:8080
    env_file:
      - .env